import ExcelJS from 'exceljs';
import type { ExportOptions } from './types';
import { currencyNumFmt, dateNumFmt, formatCellText } from './types';

function sanitizeSheetName(name: string): string {
  // Excel sheet names: max 31 chars, no : \ / ? * [ ]
  const cleaned = name.replace(/[:\\/?*[\]]/g, ' ').trim();
  return cleaned.length > 31 ? cleaned.slice(0, 31) : cleaned || 'Report';
}

function formatDateTimestamp(): string {
  return new Date().toLocaleString('en-IN', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}

function triggerDownload(buffer: ArrayBuffer, filename: string): void {
  const blob = new Blob([buffer], {
    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename.endsWith('.xlsx') ? filename : `${filename}.xlsx`;
  link.click();
  URL.revokeObjectURL(url);
}

/**
 * Builds a professional .xlsx workbook:
 *  - Business name (bold, large) + report title + generated date/time + generated by
 *  - Bold header row with brand fill + white text
 *  - Frozen header row, auto filter, auto column widths
 *  - Currency / date number formats applied per column type
 *  - Alternating row fill for readability
 */
export async function exportToExcel(options: ExportOptions): Promise<void> {
  const {
    title,
    subtitle,
    worksheetName,
    filename,
    columns,
    rows,
    businessSettings,
    generatedBy,
  } = options;

  const workbook = new ExcelJS.Workbook();
  workbook.creator = generatedBy || 'Divdev ERP';
  workbook.created = new Date();

  const sheet = workbook.addWorksheet(sanitizeSheetName(worksheetName), {
    views: [{ state: 'frozen', ySplit: 1, xSplit: 0, activeCell: 'A1', showGridLines: true }],
  });

  const colCount = columns.length;
  const businessName = businessSettings?.business_name ?? 'Divdev ERP';

  // --- Title block -------------------------------------------------------
  // Row 1: Business name (bold, 14pt)
  const r1 = sheet.getCell(1, 1);
  r1.value = businessName;
  r1.font = { bold: true, size: 14, color: { argb: 'FF0F172A' } };
  sheet.mergeCells(1, 1, 1, colCount);
  sheet.getRow(1).height = 22;

  // Row 2: subtitle/contact line (address · phone · gstin)
  const contactParts: string[] = [];
  if (businessSettings?.address) contactParts.push(businessSettings.address);
  if (businessSettings?.phone) contactParts.push(`Ph: ${businessSettings.phone}`);
  if (businessSettings?.gstin) contactParts.push(`GSTIN: ${businessSettings.gstin}`);
  const r2 = sheet.getCell(2, 1);
  r2.value = contactParts.join('  •  ');
  r2.font = { size: 9, color: { argb: 'FF64748B' } };
  sheet.mergeCells(2, 1, 2, colCount);

  // Row 3: Report title (bold, 12pt, brand color)
  const r3 = sheet.getCell(3, 1);
  r3.value = title;
  r3.font = { bold: true, size: 12, color: { argb: 'FF16A34A' } };
  sheet.mergeCells(3, 1, 3, colCount);

  // Row 4: Generated date/time + generated by
  const generatedLine = `Generated: ${formatDateTimestamp()}${
    generatedBy ? `   •   By: ${generatedBy}` : ''
  }${subtitle ? `   •   ${subtitle}` : ''}`;
  const r4 = sheet.getCell(4, 1);
  r4.value = generatedLine;
  r4.font = { size: 9, italic: true, color: { argb: 'FF64748B' } };
  sheet.mergeCells(4, 1, 4, colCount);

  // Row 5: blank spacer
  sheet.getRow(5).height = 6;

  // --- Header row (row 6) ------------------------------------------------
  const headerRowNumber = 6;
  const headerRow = sheet.getRow(headerRowNumber);
  columns.forEach((col, index) => {
    const cell = headerRow.getCell(index + 1);
    cell.value = col.header;
    cell.font = { bold: true, color: { argb: 'FFFFFFFF' }, size: 11 };
    cell.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FF16A34A' },
    };
    cell.alignment = {
      horizontal: col.type === 'currency' || col.type === 'number' ? 'right' : 'left',
      vertical: 'middle',
    };
    cell.border = {
      top: { style: 'thin', color: { argb: 'FF0F172A' } },
      bottom: { style: 'thin', color: { argb: 'FF0F172A' } },
      left: { style: 'thin', color: { argb: 'FFE2E8F0' } },
      right: { style: 'thin', color: { argb: 'FFE2E8F0' } },
    };
  });
  headerRow.height = 20;

  // --- Data rows ---------------------------------------------------------
  rows.forEach((row, rowIndex) => {
    const excelRow = sheet.getRow(headerRowNumber + 1 + rowIndex);
    columns.forEach((col, colIndex) => {
      const cell = excelRow.getCell(colIndex + 1);
      const raw = row[col.key];
      const type = col.type ?? 'text';

      if (raw == null || raw === '') {
        cell.value = '';
      } else if (type === 'currency' || type === 'number') {
        const num = Number(raw);
        cell.value = Number.isFinite(num) ? num : String(raw);
        cell.numFmt = type === 'currency' ? currencyNumFmt() : '#,##0.00';
      } else if (type === 'date') {
        // Pages pass pre-formatted date strings; keep as text.
        cell.value = String(raw);
      } else {
        cell.value = String(raw);
      }

      cell.alignment = {
        horizontal: type === 'currency' || type === 'number' ? 'right' : 'left',
        vertical: 'middle',
      };

      // Alternating row fill (very light grey).
      if (rowIndex % 2 === 1) {
        cell.fill = {
          type: 'pattern',
          pattern: 'solid',
          fgColor: { argb: 'FFF8FAFC' },
        };
      }
      cell.border = {
        bottom: { style: 'thin', color: { argb: 'FFE2E8F0' } },
      };
    });
  });

  // --- Totals row (sum currency columns) ---------------------------------
  const hasTotals = rows.length > 0 && columns.some((c) => c.type === 'currency');
  if (hasTotals) {
    const totalsRow = sheet.getRow(headerRowNumber + 1 + rows.length);
    columns.forEach((col, colIndex) => {
      const cell = totalsRow.getCell(colIndex + 1);
      if (col.type === 'currency' || col.type === 'number') {
        const sum = rows.reduce((acc, r) => {
          const v = Number(r[col.key]);
          return Number.isFinite(v) ? acc + v : acc;
        }, 0);
        cell.value = sum;
        cell.numFmt = col.type === 'currency' ? currencyNumFmt() : '#,##0.00';
        cell.font = { bold: true, color: { argb: 'FF0F172A' } };
        cell.alignment = { horizontal: 'right', vertical: 'middle' };
      } else if (colIndex === 0) {
        cell.value = 'Total';
        cell.font = { bold: true, color: { argb: 'FF0F172A' } };
      }
      cell.border = { top: { style: 'thin', color: { argb: 'FF0F172A' } } };
    });
  }

  // --- Column widths -----------------------------------------------------
  columns.forEach((col, index) => {
    const headerLen = col.header.length;
    const maxDataLen = rows.reduce((max, r) => {
      const text = formatCellText(r[col.key], col.type ?? 'text');
      return Math.max(max, text.length);
    }, 0);
    const width = col.width ?? Math.max(headerLen + 2, Math.min(maxDataLen + 2, 40));
    sheet.getColumn(index + 1).width = width;
  });

  // --- Auto filter on the header row across all data ---------------------
  const lastColLetter = sheet.getColumn(colCount).letter;
  const lastRow = headerRowNumber + rows.length + (hasTotals ? 1 : 0);
  sheet.autoFilter = `A${headerRowNumber}:${lastColLetter}${lastRow}`;
  void dateNumFmt; // date cells kept as pre-formatted text; reserved for future raw dates.

  const buffer = await workbook.xlsx.writeBuffer();
  triggerDownload(buffer as ArrayBuffer, filename);
}
