import { jsPDF } from 'jspdf';
import { autoTable } from 'jspdf-autotable';
import type { ExportColumn, ExportOptions } from './types';
import { formatCellText } from './types';

const BRAND_GREEN: [number, number, number] = [22, 163, 74];
const SLATE_900: [number, number, number] = [15, 23, 42];
const SLATE_500: [number, number, number] = [100, 116, 139];
const SLATE_100: [number, number, number] = [241, 245, 249];
const WHITE: [number, number, number] = [255, 255, 255];
const ROW_ALT: [number, number, number] = [248, 250, 252];

function formatTimestamp(): string {
  return new Date().toLocaleString('en-IN', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}

/** Load a logo URL (if any) into a data URL the jsPDF can embed. */
async function loadLogoData(
  logoUrl: string | null | undefined,
): Promise<{ data: string; format: 'PNG' | 'JPEG' } | null> {
  if (!logoUrl) return null;
  try {
    const response = await fetch(logoUrl, { mode: 'cors' });
    if (!response.ok) return null;
    const blob = await response.blob();
    const isPng = blob.type.includes('png');
    const dataUrl = await blobToDataUrl(blob);
    // Validate the image can be measured before we attempt to add it.
    await new Promise<void>((resolve, reject) => {
      const img = new Image();
      img.onload = () => resolve();
      img.onerror = () => reject(new Error('logo load error'));
      img.src = dataUrl;
    });
    return { data: dataUrl, format: isPng ? 'PNG' : 'JPEG' };
  } catch {
    return null;
  }
}

function blobToDataUrl(blob: Blob): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(reader.result as string);
    reader.onerror = () => reject(reader.error);
    reader.readAsDataURL(blob);
  });
}

function buildTableRows(
  columns: ExportColumn[],
  rows: ExportOptions['rows'],
): string[][] {
  return rows.map((row) =>
    columns.map((col) => formatCellText(row[col.key], col.type ?? 'text')),
  );
}

function columnAlign(col: ExportColumn): 'left' | 'right' | 'center' {
  if (col.align) return col.align;
  if (col.type === 'currency' || col.type === 'number') return 'right';
  return 'left';
}

/**
 * Shared PDF report engine. Produces a branded A4 report with:
 *  - Header: logo + business name + address/phone/GSTIN
 *  - Centered report title + generated date/time + generated by
 *  - Auto-paginated, striped table with repeating header
 *  - Page numbers + "Generated by Divdev ERP" footer on every page
 * Reused by every list page so the ERP has one consistent report look.
 */
export async function exportToPdfReport(options: ExportOptions): Promise<void> {
  const {
    title,
    subtitle,
    filename,
    columns,
    rows,
    businessSettings,
    generatedBy,
    orientation = 'portrait',
    tableFontSize = 9,
  } = options;

  const doc = new jsPDF({
    orientation,
    unit: 'mm',
    format: 'a4',
    compress: true,
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 14;
  const contentWidth = pageWidth - margin * 2;

  const businessName = businessSettings?.business_name ?? 'Divdev ERP';
  const logo = await loadLogoData(businessSettings?.logo_url);

  // --- Header band (drawn on the first page; repeated via willDrawPage) ---
  function drawHeader(topY: number): number {
    let cursorY = topY;

    // Logo
    if (logo) {
      try {
        const logoSize = 14;
        doc.addImage(logo.data, logo.format, margin, cursorY, logoSize, logoSize, undefined, 'FAST');
      } catch {
        /* ignore malformed logo */
      }
    }

    // Business name
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.setTextColor(...SLATE_900);
    doc.text(businessName, margin + (logo ? 18 : 0), cursorY + 6);

    // Contact line
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(...SLATE_500);
    const contactParts: string[] = [];
    if (businessSettings?.address) contactParts.push(businessSettings.address);
    if (businessSettings?.phone) contactParts.push(`Ph: ${businessSettings.phone}`);
    if (businessSettings?.gstin) contactParts.push(`GSTIN: ${businessSettings.gstin}`);
    if (contactParts.length) {
      doc.text(contactParts.join('  •  '), margin + (logo ? 18 : 0), cursorY + 11);
    }

    // Right-aligned generated info
    doc.setFontSize(8);
    doc.setTextColor(...SLATE_500);
    const generatedLine = `Generated: ${formatTimestamp()}`;
    doc.text(generatedLine, pageWidth - margin, cursorY + 4, { align: 'right' });
    if (generatedBy) {
      doc.text(`By: ${generatedBy}`, pageWidth - margin, cursorY + 9, { align: 'right' });
    }

    // Header separator
    cursorY += 16;
    doc.setDrawColor(...BRAND_GREEN);
    doc.setLineWidth(0.8);
    doc.line(margin, cursorY, pageWidth - margin, cursorY);
    cursorY += 4;

    return cursorY;
  }

  // --- Title block ---
  function drawTitle(topY: number): number {
    let cursorY = topY;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.setTextColor(...BRAND_GREEN);
    doc.text(title, pageWidth / 2, cursorY, { align: 'center' });
    cursorY += 5;

    if (subtitle) {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(...SLATE_500);
      doc.text(subtitle, pageWidth / 2, cursorY, { align: 'center' });
      cursorY += 4;
    }

    doc.setFontSize(8);
    doc.setTextColor(...SLATE_500);
    doc.text(
      `${rows.length} ${rows.length === 1 ? 'record' : 'records'}`,
      pageWidth / 2,
      cursorY,
      { align: 'center' },
    );
    cursorY += 4;
    return cursorY;
  }

  // --- Footer (on every page) ---
  function drawFooter(pageNumber: number, totalPages: number) {
    const footerY = pageHeight - 8;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(...SLATE_500);
    doc.text('Generated by Divdev ERP', margin, footerY);
    doc.text(`Page ${pageNumber} of ${totalPages}`, pageWidth - margin, footerY, {
      align: 'right',
    });
  }

  const startY = drawTitle(drawHeader(margin));

  // --- Table via autotable ---
  const head = [columns.map((c) => c.header)];
  const body = buildTableRows(columns, rows);

  // Track total page count for "Page X of Y" footers.
  let finalPageCount = 1;

  autoTable(doc, {
    head,
    body,
    startY,
    margin: { top: margin, left: margin, right: margin, bottom: 16 },
    theme: 'striped',
    styles: {
      font: 'helvetica',
      fontSize: tableFontSize,
      cellPadding: 2.5,
      textColor: SLATE_900,
      lineColor: SLATE_100,
      lineWidth: 0.1,
      overflow: 'linebreak',
      valign: 'middle',
    },
    headStyles: {
      fillColor: BRAND_GREEN,
      textColor: WHITE,
      fontStyle: 'bold',
      fontSize: tableFontSize,
      halign: 'left',
    },
    alternateRowStyles: {
      fillColor: ROW_ALT,
    },
    columnStyles: Object.fromEntries(
      columns.map((col, index) => [
        index,
        { halign: columnAlign(col), cellWidth: col.width ?? 'auto' },
      ]),
    ),
    didParseCell: (data) => {
      // Align headers to match their column's alignment rule.
      if (data.section === 'head') {
        const col = columns[data.column.index];
        if (col) {
          data.cell.styles.halign = columnAlign(col);
        }
      }
    },
    willDrawPage: () => {
      // Redraw header on every new page so the brand band is consistent.
      drawHeader(margin);
    },
    didDrawPage: () => {
      finalPageCount = doc.getNumberOfPages();
    },
  });

  // --- Footers on every page ---
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i += 1) {
    doc.setPage(i);
    drawFooter(i, totalPages);
  }

  void finalPageCount;
  void contentWidth;

  doc.save(filename.endsWith('.pdf') ? filename : `${filename}.pdf`);
}
